project:
    type: default
    output-dir: docs

lang: de
dir: ltr
toc: true
toc-depth: 5
number-sections: true
crossref: 
    sec-prefix: Abschnitt
    chapters: false # If true, then the highest level screws everything up
appendix-style: default

brand: _brand.yml
format:
    dashboard:
        css: style/_style.css
        theme: 
          - brand
          - style/_custom.scss

engine: knitr
execute:
    eval: true
    echo: false
    